create extension if not exists pgcrypto;

create table if not exists app_settings (
  id integer primary key generated by default as identity,
  home_greeting_title text not null,
  home_greeting_subtitle text not null,
  home_hero_title text not null,
  home_hero_tag text not null,
  home_hero_action_label text not null,
  home_hero_pet_slug text not null,
  browse_title text not null,
  browse_total_available_count integer not null default 0,
  browse_search_placeholder text not null default '搜索品种、城市或性格'
);

create table if not exists profiles (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  role_title text not null,
  bio text not null,
  avatar_url text not null,
  completion_percent integer not null default 0 check (completion_percent between 0 and 100),
  notifications_count integer not null default 0,
  favorites_count integer not null default 0,
  active_applications_count integer not null default 0,
  recent_status_title text not null default '最近进度',
  recent_status_body text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists profile_services (
  id bigint primary key generated always as identity,
  profile_id uuid not null references profiles(id) on delete cascade,
  label text not null,
  sort_order integer not null default 0,
  unique (profile_id, label)
);

create table if not exists screen_filters (
  id bigint primary key generated always as identity,
  screen text not null check (screen in ('home', 'browse')),
  key text not null,
  label text not null,
  sort_order integer not null default 0,
  is_default boolean not null default false,
  unique (screen, key)
);

create table if not exists pets (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  display_name text not null,
  age_label text not null,
  species text not null,
  breed text not null,
  gender text not null,
  city text not null,
  district text not null,
  hero_image_url text not null,
  list_image_url text not null,
  detail_image_url text not null,
  owner_avatar_url text not null,
  detail_meta text not null,
  detail_description text not null,
  summary text not null,
  home_card_title text,
  home_card_meta text,
  home_card_tag text,
  home_card_action_label text,
  browse_card_title text,
  browse_card_meta text,
  browse_card_tag text,
  browse_card_action_label text,
  editorial_tagline text,
  editorial_title text,
  editorial_meta text,
  detail_badge text not null,
  match_score integer not null default 0 check (match_score between 0 and 100),
  trait_labels text[] not null default '{}',
  adoption_requirement_label text not null,
  health_label text not null,
  owner_name text not null,
  owner_description text not null,
  category_keys text[] not null default '{}',
  searchable_text text not null default '',
  same_day_available boolean not null default false,
  affectionate boolean not null default false,
  is_home_pick boolean not null default false,
  home_sort_order integer,
  is_browse_result boolean not null default true,
  browse_sort_order integer,
  is_editorial_pick boolean not null default false,
  editorial_sort_order integer,
  is_detail_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists favorites (
  id bigint primary key generated always as identity,
  profile_id uuid not null references profiles(id) on delete cascade,
  pet_id uuid not null references pets(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (profile_id, pet_id)
);

create table if not exists adoption_applications (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references profiles(id) on delete cascade,
  pet_id uuid not null references pets(id) on delete cascade,
  status text not null default 'reviewing' check (status in ('submitted', 'reviewing', 'approved', 'rejected')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (profile_id, pet_id)
);
