insert into app_settings (
  id,
  home_greeting_title,
  home_greeting_subtitle,
  home_hero_title,
  home_hero_tag,
  home_hero_action_label,
  home_hero_pet_slug,
  browse_title,
  browse_total_available_count,
  browse_search_placeholder
)
values (
  1,
  '嗨，准备遇见新家人',
  '今天有 18 只温柔小可爱在等你带回家',
  E'领养，不只是选择\n而是彼此被选中',
  '今日推荐 · 金毛 / 布偶',
  '开始匹配',
  'yun-duo',
  '浏览领养',
  286,
  '搜索品种、城市或性格'
)
on conflict (id) do update set
  home_greeting_title = excluded.home_greeting_title,
  home_greeting_subtitle = excluded.home_greeting_subtitle,
  home_hero_title = excluded.home_hero_title,
  home_hero_tag = excluded.home_hero_tag,
  home_hero_action_label = excluded.home_hero_action_label,
  home_hero_pet_slug = excluded.home_hero_pet_slug,
  browse_title = excluded.browse_title,
  browse_total_available_count = excluded.browse_total_available_count,
  browse_search_placeholder = excluded.browse_search_placeholder;

insert into profiles (
  id,
  display_name,
  role_title,
  bio,
  avatar_url,
  completion_percent,
  notifications_count,
  favorites_count,
  active_applications_count,
  recent_status_title,
  recent_status_body
)
values (
  '11111111-1111-1111-1111-111111111111',
  '林晓',
  '领养申请人',
  '已通过实名认证，偏好安静亲人型猫咪',
  'https://images.unsplash.com/photo-1599447292095-73ddcdf85444?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDM0ODN8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NzM1NTgxMTV8&ixlib=rb-4.1.0&q=80&w=1080',
  82,
  3,
  12,
  3,
  '最近进度',
  '最近提交的申请正在审核中，预计今天 18:00 前收到最新消息'
)
on conflict (id) do update set
  display_name = excluded.display_name,
  role_title = excluded.role_title,
  bio = excluded.bio,
  avatar_url = excluded.avatar_url,
  completion_percent = excluded.completion_percent,
  notifications_count = excluded.notifications_count,
  favorites_count = excluded.favorites_count,
  active_applications_count = excluded.active_applications_count,
  recent_status_title = excluded.recent_status_title,
  recent_status_body = excluded.recent_status_body,
  updated_at = timezone('utc', now());

insert into profile_services (profile_id, label, sort_order)
values
  ('11111111-1111-1111-1111-111111111111', '领养申请记录', 1),
  ('11111111-1111-1111-1111-111111111111', '家庭环境问卷', 2),
  ('11111111-1111-1111-1111-111111111111', '上门回访安排', 3)
on conflict (profile_id, label) do update set
  sort_order = excluded.sort_order;

insert into screen_filters (screen, key, label, sort_order, is_default)
values
  ('home', 'dog', '狗狗', 1, true),
  ('home', 'cat', '猫咪', 2, false),
  ('home', 'young', '幼宠', 3, false),
  ('home', 'small', '小型', 4, false),
  ('browse', 'all', '全部', 1, true),
  ('browse', 'same-day', '可当天看宠', 2, false),
  ('browse', 'affectionate', '亲人黏人', 3, false)
on conflict (screen, key) do update set
  label = excluded.label,
  sort_order = excluded.sort_order,
  is_default = excluded.is_default;

insert into pets (
  id,
  slug,
  display_name,
  age_label,
  species,
  breed,
  gender,
  city,
  district,
  hero_image_url,
  list_image_url,
  detail_image_url,
  owner_avatar_url,
  detail_meta,
  detail_description,
  summary,
  home_card_title,
  home_card_meta,
  home_card_tag,
  home_card_action_label,
  browse_card_title,
  browse_card_meta,
  browse_card_tag,
  browse_card_action_label,
  editorial_tagline,
  editorial_title,
  editorial_meta,
  detail_badge,
  match_score,
  trait_labels,
  adoption_requirement_label,
  health_label,
  owner_name,
  owner_description,
  category_keys,
  searchable_text,
  same_day_available,
  affectionate,
  is_home_pick,
  home_sort_order,
  is_browse_result,
  browse_sort_order,
  is_editorial_pick,
  editorial_sort_order,
  is_detail_default
)
values
  (
    '20000000-0000-0000-0000-000000000001',
    'nai-you',
    '奶油',
    '2岁',
    '猫',
    '布偶猫',
    '女生',
    '上海',
    '徐汇',
    'https://images.unsplash.com/photo-1589536426527-70d912bbff36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1589536426527-70d912bbff36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1589536426527-70d912bbff36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1645398049945-55498bbbe472?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    '2岁 · 布偶猫 · 上海徐汇',
    '奶油性格温和，喜欢被轻轻抱起，也很适合和第一次养猫的人一起建立稳定陪伴关系。',
    '亲人、会撒娇，适合安静家庭。',
    '奶油｜2岁',
    E'布偶猫 · 女生 · 已驱虫\n亲人、会撒娇，适合安静家庭。',
    '上海 · 可当天见面',
    '预约',
    '奶油｜布偶',
    '亲人柔软 · 适合居家陪伴',
    '上海 · 可当天见面',
    '查看详情',
    null,
    null,
    null,
    '已完成驱虫',
    96,
    array['亲人黏人', '适合新手'],
    '接受回访',
    '已驱虫',
    '救助人 · 阿岚',
    '平均 5 分钟内回复，支持视频看猫',
    array['cat'],
    '奶油 布偶猫 上海 徐汇 亲人 会撒娇 安静家庭',
    true,
    true,
    true,
    1,
    false,
    null,
    false,
    null,
    false
  ),
  (
    '20000000-0000-0000-0000-000000000002',
    'li-zi',
    '栗子',
    '1岁',
    '狗',
    '柯基犬',
    '男生',
    '上海',
    '浦东',
    'https://images.unsplash.com/photo-1549119576-31fcceff6a38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1549119576-31fcceff6a38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1549119576-31fcceff6a38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1561037404-61cd46aa615b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    '1岁 · 柯基犬 · 上海浦东',
    '栗子精力充沛、喜欢陪人散步，适合节奏稳定又愿意和它多互动的家庭。',
    '爱散步、爱互动，适合有活力的家。',
    '栗子｜1岁',
    E'柯基犬 · 男生 · 已绝育\n爱散步、爱互动，适合有活力的家。',
    '浦东 · 周末可探访',
    '收藏',
    '栗子｜柯基',
    '活泼外向 · 喜欢和人互动',
    '上海 · 周末可探访',
    '查看详情',
    null,
    null,
    null,
    '已完成体检',
    91,
    array['活泼亲人', '喜欢散步'],
    '稳定遛狗时间',
    '已绝育',
    '救助人 · 周周',
    '支持周末线下见面，适合城市家庭',
    array['dog', 'small'],
    '栗子 柯基犬 上海 浦东 活泼 互动 可探访',
    false,
    true,
    true,
    2,
    false,
    null,
    false,
    null,
    false
  ),
  (
    '20000000-0000-0000-0000-000000000003',
    'yun-duo',
    '云朵',
    '2岁',
    '狗',
    '萨摩耶',
    '女生',
    '北京',
    '朝阳',
    'https://images.unsplash.com/photo-1569551739860-2d34c88ca3cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1569551739860-2d34c88ca3cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1569551739860-2d34c88ca3cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    '2岁 · 萨摩耶 · 北京朝阳',
    '云朵会主动迎接每一个靠近它的人，性格阳光，非常适合喜欢户外活动和互动陪伴的家庭。',
    '笑容值满格，喜欢互动，适合需要治愈感的日常生活。',
    null,
    null,
    null,
    null,
    '云朵｜萨摩耶',
    '爱笑亲人 · 喜欢和家人待在一起',
    '北京 · 预约见面',
    '查看详情',
    '人气 TOP 1 · 超亲人',
    E'云朵｜萨摩耶\n笑容值满格的小太阳',
    '2岁 · 北京 · 已体检',
    '已完成体检',
    94,
    array['亲人黏人', '适合家庭'],
    '接受陪伴训练',
    '已体检',
    '救助人 · 米娅',
    '支持视频连线，适合有户外时间的家庭',
    array['dog'],
    '云朵 萨摩耶 北京 朝阳 亲人 爱笑 户外',
    true,
    true,
    false,
    null,
    false,
    null,
    true,
    1,
    false
  ),
  (
    '20000000-0000-0000-0000-000000000004',
    'nuo-mi',
    '糯米',
    '2岁',
    '猫',
    '英短',
    '女生',
    '杭州',
    '西湖',
    'https://images.unsplash.com/photo-1757233363052-fc6daa6bf18c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1757233363052-fc6daa6bf18c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1757233363052-fc6daa6bf18c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1517841905240-472988babdf9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    '2岁 · 英短 · 杭州西湖',
    '糯米安静、稳定，喜欢窝在柔软角落里陪伴人，非常适合想要温柔陪伴的新手家庭。',
    '安静温柔，适合新手家庭。',
    null,
    null,
    null,
    null,
    '糯米｜英短',
    '安静温柔 · 适合新手家庭',
    '杭州 · 视频先看',
    null,
    null,
    null,
    null,
    '已完成疫苗',
    93,
    array['安静黏人', '适合公寓'],
    '接受室内喂养',
    '已完成疫苗',
    '救助人 · 阿岚',
    '支持视频看猫，平均 5 分钟内回复',
    array['cat'],
    '糯米 英短 杭州 西湖 安静 温柔 新手',
    false,
    false,
    false,
    null,
    true,
    1,
    false,
    null,
    false
  ),
  (
    '20000000-0000-0000-0000-000000000005',
    'ke-ke',
    '可可',
    '3岁',
    '狗',
    '米克斯',
    '男生',
    '深圳',
    '南山',
    'https://images.unsplash.com/photo-1681641485014-16df0b86a45b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1681641485014-16df0b86a45b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1681641485014-16df0b86a45b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    '3岁 · 米克斯 · 深圳南山',
    '可可会等门、会握手，对陌生环境适应力好，适合希望尽快建立默契的家庭。',
    '会握手会等门，亲人稳定。',
    null,
    null,
    null,
    null,
    '可可｜米克斯',
    '会握手会等门 · 亲人稳定',
    '深圳 · 可带回试住',
    '联系救助站',
    null,
    null,
    null,
    '可试住',
    90,
    array['亲人稳定', '适合家庭'],
    '保持规律作息',
    '已绝育',
    '救助人 · 夏夏',
    '支持试住评估，适合有稳定作息的家庭',
    array['dog'],
    '可可 米克斯 深圳 南山 稳定 试住',
    false,
    true,
    false,
    null,
    true,
    2,
    false,
    null,
    false
  ),
  (
    '20000000-0000-0000-0000-000000000006',
    'nai-tang',
    '奶糖',
    '2岁',
    '猫',
    '英短蓝猫',
    '女生',
    '上海',
    '浦东',
    'https://images.unsplash.com/photo-1770734027339-124b18ecd88b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1770734027339-124b18ecd88b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1770734027339-124b18ecd88b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    'https://images.unsplash.com/photo-1645398049945-55498bbbe472?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    '2岁 · 英短蓝猫 · 上海浦东',
    '奶糖曾被救助于社区车库，已经完成体检、驱虫和基础疫苗。它喜欢安静环境，会主动靠近人类，也能独处，是非常适合新手领养人的陪伴型猫咪。',
    '安静陪伴型猫咪，适合新手领养人。',
    null,
    null,
    null,
    null,
    '奶糖｜英短蓝猫',
    '安静陪伴型 · 适合新手家庭',
    '上海 · 可预约探访',
    '查看详情',
    null,
    null,
    null,
    '已完成疫苗',
    98,
    array['安静黏人', '适合公寓'],
    '接受回访',
    '已绝育',
    '救助人 · 阿岚',
    '平均 5 分钟内回复，支持视频看猫',
    array['cat'],
    '奶糖 英短蓝猫 上海 浦东 安静 公寓 新手',
    false,
    true,
    false,
    null,
    false,
    null,
    false,
    null,
    true
  )
on conflict (slug) do update set
  display_name = excluded.display_name,
  age_label = excluded.age_label,
  species = excluded.species,
  breed = excluded.breed,
  gender = excluded.gender,
  city = excluded.city,
  district = excluded.district,
  hero_image_url = excluded.hero_image_url,
  list_image_url = excluded.list_image_url,
  detail_image_url = excluded.detail_image_url,
  owner_avatar_url = excluded.owner_avatar_url,
  detail_meta = excluded.detail_meta,
  detail_description = excluded.detail_description,
  summary = excluded.summary,
  home_card_title = excluded.home_card_title,
  home_card_meta = excluded.home_card_meta,
  home_card_tag = excluded.home_card_tag,
  home_card_action_label = excluded.home_card_action_label,
  browse_card_title = excluded.browse_card_title,
  browse_card_meta = excluded.browse_card_meta,
  browse_card_tag = excluded.browse_card_tag,
  browse_card_action_label = excluded.browse_card_action_label,
  editorial_tagline = excluded.editorial_tagline,
  editorial_title = excluded.editorial_title,
  editorial_meta = excluded.editorial_meta,
  detail_badge = excluded.detail_badge,
  match_score = excluded.match_score,
  trait_labels = excluded.trait_labels,
  adoption_requirement_label = excluded.adoption_requirement_label,
  health_label = excluded.health_label,
  owner_name = excluded.owner_name,
  owner_description = excluded.owner_description,
  category_keys = excluded.category_keys,
  searchable_text = excluded.searchable_text,
  same_day_available = excluded.same_day_available,
  affectionate = excluded.affectionate,
  is_home_pick = excluded.is_home_pick,
  home_sort_order = excluded.home_sort_order,
  is_browse_result = excluded.is_browse_result,
  browse_sort_order = excluded.browse_sort_order,
  is_editorial_pick = excluded.is_editorial_pick,
  editorial_sort_order = excluded.editorial_sort_order,
  is_detail_default = excluded.is_detail_default;
